![](../img/chinahadoop.png)

# Numpy&&Pandas教程(上)

**[小象学院](http://www.chinahadoop.cn/course/landpage/15)《机器学习集训营》课程资料 by [@寒小阳](https://www.chinahadoop.cn/user/49339/about)**

## [Pandas](http://pandas.pydata.org/)简介
- python数据分析library
- 基于numpy (对ndarray的操作)
- 有一种用python做Excel/SQL/R的感觉
- 为什么要学习pandas?
    - pandas和机器学习的关系，数据预处理，feature engineering。
    - pandas的DataFrame结构和大家在大数据部分见到的spark中的DataFrame非常类似。

## 目录
- numpy速成
- Series
- DataFrame
- Index
- 文件读写

## Numpy简介

- Numpy是Python语言的一个library [numpy](http://www.numpy.org/)
- Numpy主要支持矩阵操作和运算
- 现在比较流行的机器学习框架（例如Tensorflow/PyTorch等等），语法都与Numpy比较接近

### Arrays/数组

In [1]:
%config ZMQInteractiveShell.ast_node_interactivity='all'
%pprint
import numpy as np

Pretty printing has been turned OFF


In [2]:
#嵌套list转numpy array
a = np.array([[1,2,3], [4,5,6]])
a
type(a)

array([[1, 2, 3],
       [4, 5, 6]])

<class 'numpy.ndarray'>

In [3]:
# 随机生成array
b= np.random.random((2,2))
b

array([[0.10087053, 0.63939648],
       [0.59549604, 0.58352624]])

In [4]:
# 查看维度
a=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[2,4,5]]])
a
a.shape

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 4, 5]]])

(2, 2, 3)

In [5]:
print(a.shape, b.shape, a.dtype, b.dtype)

(2, 2, 3) (2, 2) int64 float64


In [6]:
# astype做类型转换
a.astype(np.float)

array([[[1., 2., 3.],
        [4., 5., 6.]],

       [[1., 2., 3.],
        [2., 4., 5.]]])

### 数组索引与切片/Array indexing and slicing
![](../img/numpy-index.png)

In [7]:
a
a[0,1]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 4, 5]]])

array([4, 5, 6])

In [8]:
a
a[:, 1:3]

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 4, 5]]])

array([[[4, 5, 6]],

       [[2, 4, 5]]])

In [9]:
a.size

12

### boolean indexing
![](../img/numpy-bool-index.png)

In [10]:
a
a > 2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 4, 5]]])

array([[[False, False,  True],
        [ True,  True,  True]],

       [[False, False,  True],
        [False,  True,  True]]])

In [11]:
a[a>2] #根据条件选择

array([3, 4, 5, 6, 3, 4, 5])

In [12]:
a[a>2] = 0 #根据条件选择数据进行赋值
a

array([[[1, 2, 0],
        [0, 0, 0]],

       [[1, 2, 0],
        [2, 0, 0]]])

### 数学运算

In [13]:
a
a.shape

array([[[1, 2, 0],
        [0, 0, 0]],

       [[1, 2, 0],
        [2, 0, 0]]])

(2, 2, 3)

In [14]:
c = np.random.random((2,3))
c
c.shape

array([[0.57104354, 0.82210532, 0.99865874],
       [0.63489647, 0.51821603, 0.1772419 ]])

(2, 3)

In [15]:
a + c

array([[[1.57104354, 2.82210532, 0.99865874],
        [0.63489647, 0.51821603, 0.1772419 ]],

       [[1.57104354, 2.82210532, 0.99865874],
        [2.63489647, 0.51821603, 0.1772419 ]]])

In [16]:
a - c

array([[[ 0.42895646,  1.17789468, -0.99865874],
        [-0.63489647, -0.51821603, -0.1772419 ]],

       [[ 0.42895646,  1.17789468, -0.99865874],
        [ 1.36510353, -0.51821603, -0.1772419 ]]])

In [17]:
a * c

array([[[0.57104354, 1.64421064, 0.        ],
        [0.        , 0.        , 0.        ]],

       [[0.57104354, 1.64421064, 0.        ],
        [1.26979293, 0.        , 0.        ]]])

In [18]:
a / c

array([[[1.75117995, 2.43277832, 0.        ],
        [0.        , 0.        , 0.        ]],

       [[1.75117995, 2.43277832, 0.        ],
        [3.15011991, 0.        , 0.        ]]])

### 广播特性/boardcasting
![](../img/numpy-broadcast.png)

In [19]:
a + 2 #类似于上图1

array([[[3, 4, 2],
        [2, 2, 2]],

       [[3, 4, 2],
        [4, 2, 2]]])

In [20]:
c = np.random.random((1,3))
c

array([[0.93062242, 0.29471495, 0.89453985]])

In [21]:
a

array([[[1, 2, 0],
        [0, 0, 0]],

       [[1, 2, 0],
        [2, 0, 0]]])

In [22]:
a + c #维度(2,2,3)和(1,3)的array相加，基于广播特性，最后得到维度(2,2,3)的array

array([[[1.93062242, 2.29471495, 0.89453985],
        [0.93062242, 0.29471495, 0.89453985]],

       [[1.93062242, 2.29471495, 0.89453985],
        [2.93062242, 0.29471495, 0.89453985]]])

![](../img/numpy-broadcast.png)
当操作两个array时，numpy会逐个dimension比较它们的shape，在下述情况下，两arrays会兼容和输出broadcasting结果：<br>

1. 相等
2. 其中一个为1，（进而可进行拷贝拓展已至，shape匹配）
3. 当两个ndarray的维度不完全相同的时候，rank较小的那个ndarray会被自动在前面加上一个一维维度，直到与另一个ndarray rank相同再检查是否匹配

比如求和的时候有：
```python
Image (3d array):  256 x 256 x 3
Scale (1d array):              3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

A      (2d array):  5 x 4
B      (1d array):      1
Result (2d array):  5 x 4

A      (2d array):  15 x 3 x 5
B      (1d array):  15 x 1 x 5
Result (2d array):  15 x 3 x 5
```

In [23]:
a=np.random.random((8,1,6))
b=np.random.random((1,6,1))
(a+b).shape

(8, 6, 6)

### 统计数学运算

In [24]:
a
np.sum(a) #全部元素求和

array([[[0.13169241, 0.12076024, 0.94718171, 0.9868782 , 0.52460178,
         0.7050304 ]],

       [[0.75982848, 0.12849312, 0.99862352, 0.57892246, 0.93388848,
         0.27688479]],

       [[0.84861432, 0.46856831, 0.91133697, 0.43440833, 0.73288593,
         0.55042371]],

       [[0.14429995, 0.43673552, 0.39708228, 0.23377411, 0.81263233,
         0.53145192]],

       [[0.42747949, 0.99082152, 0.09460188, 0.02920687, 0.86489352,
         0.25205818]],

       [[0.15014402, 0.66933541, 0.54412228, 0.80764711, 0.09997845,
         0.73227461]],

       [[0.01941847, 0.97843217, 0.28262159, 0.27665419, 0.8822287 ,
         0.37638411]],

       [[0.35989009, 0.39787517, 0.83485582, 0.60017681, 0.86968622,
         0.18526147]]])

25.321047407612056

In [25]:
np.sum(a, axis=0) #按照第1个维度汇总求和

array([[2.84136723, 4.19102145, 5.01042605, 3.94766809, 5.72079541,
        3.60976919]])

In [26]:
np.sum(a, axis=2) #按照第3个维度汇总求和

array([[3.41614474],
       [3.67664086],
       [3.94623755],
       [2.55597611],
       [2.65906146],
       [3.00350189],
       [2.81573922],
       [3.24774558]])

In [27]:
np.mean(a, axis=2) #按照第3个维度汇总求均值

array([[0.56935746],
       [0.61277348],
       [0.65770626],
       [0.42599602],
       [0.44317691],
       [0.50058365],
       [0.46928987],
       [0.54129093]])

### 乘法

```
np.dot是点乘(矩阵乘法)
|A B| . |E F| = |A*E+B*G A*F+B*H|
|C D|   |G H|   |C*E+D*G C*F+D*H|

np.multiply是逐元素乘法
|A B| ⊙ |E F| = |A*E B*F|
|C D|   |G H|   |C*G D*H|
```

In [28]:
a = np.array([[1,2], [3,4]])
b = np.array([[1,2], [2,3]])
a
b

array([[1, 2],
       [3, 4]])

array([[1, 2],
       [2, 3]])

In [29]:
np.dot(a,b)

array([[ 5,  8],
       [11, 18]])

In [30]:
np.multiply(a,b)

array([[ 1,  4],
       [ 6, 12]])

## Pandas数据结构Series

### 构造和初始化Series

In [31]:
import pandas as pd

In [32]:
pd.__version__ #查看版本，不同版本的pandas功能有一些差异

'0.24.2'

Series是一个一维的数据结构，下面是一些初始化Series的方法。

In [33]:
s = pd.Series([7, 'Beijing', 2.17, -12344, 'Happy Birthday!'])
s

0                  7
1            Beijing
2               2.17
3             -12344
4    Happy Birthday!
dtype: object

In [34]:
s = pd.Series([7, 'Beijing', 2.17, -12344, 'Happy Birthday!'])
s

0                  7
1            Beijing
2               2.17
3             -12344
4    Happy Birthday!
dtype: object

pandas会默认用0到n-1来作为Series的index，但是我们也可以自己指定index。index我们可以把它理解为dict里面的key。

In [35]:
s = pd.Series([7, 'Beijing', 2.17, -12344, 'Happy Birthday!'],
             index=['A', 'B', 'C', 'D', 'E'])
s

A                  7
B            Beijing
C               2.17
D             -12344
E    Happy Birthday!
dtype: object

还可以用dictionary来构造一个Series，因为Series本来就是key value pairs。

In [36]:
cities = {'Beijing': 55000, 'Shanghai': 60000, 'Shenzhen': 50000, 'Hangzhou': 20000, 'Guangzhou': 25000, 'Suzhou': None}
apts = pd.Series(cities, name="price")
apts

Beijing      55000.0
Shanghai     60000.0
Shenzhen     50000.0
Hangzhou     20000.0
Guangzhou    25000.0
Suzhou           NaN
Name: price, dtype: float64

numpy ndarray构建一个Series

In [37]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s

a   -1.480891
b    0.315682
c    0.109896
d   -0.963698
e    0.834620
dtype: float64

### 选择数据

我们可以像对待一个list一样对待Series

In [38]:
apts[1:] #切片

Shanghai     60000.0
Shenzhen     50000.0
Hangzhou     20000.0
Guangzhou    25000.0
Suzhou           NaN
Name: price, dtype: float64

In [39]:
apts[:-1] #切片

Beijing      55000.0
Shanghai     60000.0
Shenzhen     50000.0
Hangzhou     20000.0
Guangzhou    25000.0
Name: price, dtype: float64

In [40]:
apts[[4,3,1]] #这种写法是Series独有而list不具备的

Guangzhou    25000.0
Hangzhou     20000.0
Shanghai     60000.0
Name: price, dtype: float64

为什么下面这样会拿到两个NaN呢？

In [41]:
apts[1:] + apts[:-1] #注意，在相加的时候，其实是index对齐的方式相加的

Beijing           NaN
Guangzhou     50000.0
Hangzhou      40000.0
Shanghai     120000.0
Shenzhen     100000.0
Suzhou            NaN
Name: price, dtype: float64

Series就像一个dict，前面定义的index就是用来选择数据的

In [42]:
apts["Hangzhou"]

20000.0

In [43]:
apts[["Hangzhou", "Beijing", "Shenzhen"]]

Hangzhou    20000.0
Beijing     55000.0
Shenzhen    50000.0
Name: price, dtype: float64

In [44]:
"Hangzhou" in apts #判断是否有这个index

True

In [45]:
"Chongqing" in apts

False

比较安全的用key读取value的方法如下

In [46]:
apts.get("Chongqing", 55) #和字典类似，默认值放在后面

55

In [47]:
apts.get("Hangzhou", 0)

20000.0

下面这种写法，如果key不存在，就可能会报错了

In [48]:
# apts["Chongqing"]

boolean indexing，与numpy类似。

In [49]:
apts[apts < 50000] #条件选择

Hangzhou     20000.0
Guangzhou    25000.0
Name: price, dtype: float64

In [50]:
apts.median() #中位数，统计计算

50000.0

In [51]:
apts[apts > apts.median()] #借助于统计计算的数据选择

Beijing     55000.0
Shanghai    60000.0
Name: price, dtype: float64

下面我再详细展示一下这个boolean indexing是如何工作的

In [52]:
less_than_50000 = apts < 50000
less_than_50000 #实际上拿到的是一个True or False的series

Beijing      False
Shanghai     False
Shenzhen     False
Hangzhou      True
Guangzhou     True
Suzhou       False
Name: price, dtype: bool

In [53]:
print(apts[less_than_50000])

Hangzhou     20000.0
Guangzhou    25000.0
Name: price, dtype: float64


### Series元素赋值

Series的元素可以被赋值

In [54]:
#根据index赋值
print("Old value: ", apts['Shenzhen'])
apts['Shenzhen'] = 55000
print("New value: ", apts['Shenzhen'])

Old value:  50000.0
New value:  55000.0


前面讲过的boolean indexing在赋值的时候也可以用

In [55]:
# 条件选择赋值
print(apts[apts < 50000])
print()
apts[apts <= 50000] = 40000
print(apts[apts < 50000])

Hangzhou     20000.0
Guangzhou    25000.0
Name: price, dtype: float64

Hangzhou     40000.0
Guangzhou    40000.0
Name: price, dtype: float64


### 数学运算

下面我们来讲一些基本的数学运算。

In [56]:
apts / 2 #广播特性

Beijing      27500.0
Shanghai     30000.0
Shenzhen     27500.0
Hangzhou     20000.0
Guangzhou    20000.0
Suzhou           NaN
Name: price, dtype: float64

In [57]:
apts ** 2 #广播特性

Beijing      3.025000e+09
Shanghai     3.600000e+09
Shenzhen     3.025000e+09
Hangzhou     1.600000e+09
Guangzhou    1.600000e+09
Suzhou                NaN
Name: price, dtype: float64

numpy的运算可以被运用到pandas上去

In [58]:
np.square(apts)

Beijing      3.025000e+09
Shanghai     3.600000e+09
Shenzhen     3.025000e+09
Hangzhou     1.600000e+09
Guangzhou    1.600000e+09
Suzhou                NaN
Name: price, dtype: float64

我们再定义一个新的Series做加法

In [59]:
cars = pd.Series({'Beijing': 300000, 'Shanghai': 400000, 'Shenzhen': 300000, \
                      'Tianjin': 200000, 'Guangzhou': 200000, 'Chongqing': 150000})
cars

Beijing      300000
Shanghai     400000
Shenzhen     300000
Tianjin      200000
Guangzhou    200000
Chongqing    150000
dtype: int64

In [60]:
print(cars + apts * 100) #注意广播特性与index对齐求和

Beijing      5800000.0
Chongqing          NaN
Guangzhou    4200000.0
Hangzhou           NaN
Shanghai     6400000.0
Shenzhen     5800000.0
Suzhou             NaN
Tianjin            NaN
dtype: float64


## 数据结构[Dataframe](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)

一个Dataframe就是一张表格，Series表示的是一维数组，Dataframe则是一个二维数组，可以类比成一张excel的spreadsheet。也可以把Dataframe当做一组Series的集合。

### 创建一个DataFrame

dataframe可以由一个dictionary构造得到。

In [1]:
import pandas as pd
data = {'city': ['Beijing', 'Shanghai', 'Guangzhou', 'Shenzhen', 'Hangzhou', 'Chongqing'],
       'year': [2016,2017,2016,2017,2016, 2016],
       'population': [2100, 2300, 1000, 700, 500, 500]}
pd.DataFrame(data)

city  year  population
0    Beijing  2016        2100
1   Shanghai  2017        2300
2  Guangzhou  2016        1000
3   Shenzhen  2017         700
4   Hangzhou  2016         500
5  Chongqing  2016         500

columns的名字和顺序可以指定

In [2]:
pd.DataFrame(data, columns=['year', 'city', 'population'])

year       city  population
0  2016    Beijing        2100
1  2017   Shanghai        2300
2  2016  Guangzhou        1000
3  2017   Shenzhen         700
4  2016   Hangzhou         500
5  2016  Chongqing         500

index也可以指定

In [3]:
frame = pd.DataFrame(data, columns = ['year', 'city', 'population'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame

year       city  population
one    2016    Beijing        2100
two    2017   Shanghai        2300
three  2016  Guangzhou        1000
four   2017   Shenzhen         700
five   2016   Hangzhou         500
six    2016  Chongqing         500

也可以从几个Series构建一个DataFrame

In [64]:
apts

Beijing      55000.0
Shanghai     60000.0
Shenzhen     55000.0
Hangzhou     40000.0
Guangzhou    40000.0
Suzhou           NaN
Name: price, dtype: float64

In [65]:
cars

Beijing      300000
Shanghai     400000
Shenzhen     300000
Tianjin      200000
Guangzhou    200000
Chongqing    150000
dtype: int64

In [66]:
# index会对齐
df = pd.DataFrame({"apts": apts, "cars": cars})
df

apts      cars
Beijing    55000.0  300000.0
Chongqing      NaN  150000.0
Guangzhou  40000.0  200000.0
Hangzhou   40000.0       NaN
Shanghai   60000.0  400000.0
Shenzhen   55000.0  300000.0
Suzhou         NaN       NaN
Tianjin        NaN  200000.0

也可以用一个list of dicts来构建DataFrame

In [67]:
data = [{"BOSS": 999999, "Jason": 50000, "Han": 1000}, {"BOSS": 99999, "Jason": 8000, "Han": 200}]
pd.DataFrame(data,columns=['BOSS','Han','Jason'])

BOSS   Han  Jason
0  999999  1000  50000
1   99999   200   8000

In [68]:
pd.DataFrame(data, index=["salary", "bonus"])

BOSS   Han  Jason
salary  999999  1000  50000
bonus    99999   200   8000

In [69]:
df["apts"]

Beijing      55000.0
Chongqing        NaN
Guangzhou    40000.0
Hangzhou     40000.0
Shanghai     60000.0
Shenzhen     55000.0
Suzhou           NaN
Tianjin          NaN
Name: apts, dtype: float64

In [70]:
df["total_cost"] = df["apts"]*100 + df["cars"]
df

apts      cars  total_cost
Beijing    55000.0  300000.0   5800000.0
Chongqing      NaN  150000.0         NaN
Guangzhou  40000.0  200000.0   4200000.0
Hangzhou   40000.0       NaN         NaN
Shanghai   60000.0  400000.0   6400000.0
Shenzhen   55000.0  300000.0   5800000.0
Suzhou         NaN       NaN         NaN
Tianjin        NaN  200000.0         NaN

In [71]:
# 注意一下Series与DataFrame的区别
frame['city'] #Series
type(frame['city'])
frame[['city']] #DataFrame
type(frame[['city']])

one        Beijing
two       Shanghai
three    Guangzhou
four      Shenzhen
five      Hangzhou
six      Chongqing
Name: city, dtype: object

<class 'pandas.core.series.Series'>

city
one      Beijing
two     Shanghai
three  Guangzhou
four    Shenzhen
five    Hangzhou
six    Chongqing

<class 'pandas.core.frame.DataFrame'>

loc方法可以拿到行

In [72]:
# loc+index取出行
frame.loc['three']
type(frame.loc['three'])

year               2016
city          Guangzhou
population         1000
Name: three, dtype: object

<class 'pandas.core.series.Series'>

iloc方法可以拿到行和列，把pandas dataframe当做numpy的ndarray来操作

In [73]:
frame.head()

year       city  population
one    2016    Beijing        2100
two    2017   Shanghai        2300
three  2016  Guangzhou        1000
four   2017   Shenzhen         700
five   2016   Hangzhou         500

In [74]:
frame.iloc[1:3, 2:4] #类似于numpy的切片

population
two          2300
three        1000

### DataFrame数据选择与赋值

大多数情况下，我们的赋值操作都是在**数据选择**之后进行赋值的，DataFrame的数据选择有很多不同的函数，相对比较自由。但是建议大家使用**loc函数**进行数据选择。

具体的语法为**df.loc\[行条件,列条件\]**

In [75]:
frame

year       city  population
one    2016    Beijing        2100
two    2017   Shanghai        2300
three  2016  Guangzhou        1000
four   2017   Shenzhen         700
five   2016   Hangzhou         500
six    2016  Chongqing         500

In [76]:
frame.loc["one","population"] = 2200
frame

year       city  population
one    2016    Beijing        2200
two    2017   Shanghai        2300
three  2016  Guangzhou        1000
four   2017   Shenzhen         700
five   2016   Hangzhou         500
six    2016  Chongqing         500

可以给一整列赋值

In [77]:
frame.loc[:,'debt'] = 100
frame

year       city  population  debt
one    2016    Beijing        2200   100
two    2017   Shanghai        2300   100
three  2016  Guangzhou        1000   100
four   2017   Shenzhen         700   100
five   2016   Hangzhou         500   100
six    2016  Chongqing         500   100

In [78]:
frame.loc['six',:] = 0
frame

year       city  population  debt
one    2016    Beijing        2200   100
two    2017   Shanghai        2300   100
three  2016  Guangzhou        1000   100
four   2017   Shenzhen         700   100
five   2016   Hangzhou         500   100
six       0          0           0     0

我们可以给定多个条件进行组合，选择对应的数据。每个条件用小括号包裹，同时通过&(与) |(或) ~(非)进行组合。

In [79]:
frame.loc[(frame['year']==2016)&(frame['city']!='Shanghai')&(frame['population']>=1000),:]

year       city  population  debt
one    2016    Beijing        2200   100
three  2016  Guangzhou        1000   100

In [80]:
frame.loc[(frame['year']==2016)|(frame['population']>=1000),['year','city','population']]

year       city  population
one    2016    Beijing        2200
two    2017   Shanghai        2300
three  2016  Guangzhou        1000
five   2016   Hangzhou         500

还可以用Series来指定需要修改的index以及相对应的value，没有指定的默认用NaN.

In [81]:
val = pd.Series([100, 200, 300], index=['two', 'three', 'five'])
frame['debt'] = val
print(frame)

       year       city  population   debt
one    2016    Beijing        2200    NaN
two    2017   Shanghai        2300  100.0
three  2016  Guangzhou        1000  200.0
four   2017   Shenzhen         700    NaN
five   2016   Hangzhou         500  300.0
six       0          0           0    NaN


如果我们想要知道有哪些列，直接用columns

In [82]:
print(frame.columns)

Index(['year', 'city', 'population', 'debt'], dtype='object')


行的话就叫做index啦

In [83]:
frame.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

一个DataFrame就和一个numpy 2d array一样，可以被转置

In [84]:
pop = {'Beijing': {2016: 2100, 2017:2200},
      'Shanghai': {2015:2400, 2016:2500, 2017:2600}}

In [85]:
frame.T

one       two      three      four      five  six
year           2016      2017       2016      2017      2016    0
city        Beijing  Shanghai  Guangzhou  Shenzhen  Hangzhou    0
population     2200      2300       1000       700       500    0
debt            NaN       100        200       NaN       300  NaN

### csv文件读写

- [read_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html)
- [to_csv](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html)

In [15]:
import pandas as pd
pokemon = pd.read_csv("../data/Pokemon.csv")
pokemon.head(10)

#                       Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1                  Bulbasaur  Grass  Poison    318  45      49       49   
1  2                    Ivysaur  Grass  Poison    405  60      62       63   
2  3                   Venusaur  Grass  Poison    525  80      82       83   
3  3      VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4                 Charmander   Fire     NaN    309  39      52       43   
5  5                 Charmeleon   Fire     NaN    405  58      64       58   
6  6                  Charizard   Fire  Flying    534  78      84       78   
7  6  CharizardMega Charizard X   Fire  Dragon    634  78     130      111   
8  6  CharizardMega Charizard Y   Fire  Flying    634  78     104       78   
9  7                   Squirtle  Water     NaN    314  44      48       65   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False  
5       80       65     80           1      False  
6      109       85    100           1      False  
7      130       85    100           1      False  
8      159      115    100           1      False  
9       50       64     43           1      False

In [87]:
#describe可以帮我们了解数据的统计特性
pokemon.describe()

#      Total          HP      Attack     Defense     Sp. Atk  \
count  800.000000  800.00000  800.000000  800.000000  800.000000  800.000000   
mean   362.813750  435.10250   69.258750   79.001250   73.842500   72.820000   
std    208.343798  119.96304   25.534669   32.457366   31.183501   32.722294   
min      1.000000  180.00000    1.000000    5.000000    5.000000   10.000000   
25%    184.750000  330.00000   50.000000   55.000000   50.000000   49.750000   
50%    364.500000  450.00000   65.000000   75.000000   70.000000   65.000000   
75%    539.250000  515.00000   80.000000  100.000000   90.000000   95.000000   
max    721.000000  780.00000  255.000000  190.000000  230.000000  194.000000   

          Sp. Def       Speed  Generation  
count  800.000000  800.000000   800.00000  
mean    71.902500   68.277500     3.32375  
std     27.828916   29.060474     1.66129  
min     20.000000    5.000000     1.00000  
25%     50.000000   45.000000     2.00000  
50%     70.000000   65.000000     3.00000  
75%     90.000000   90.000000     5.00000  
max    230.000000  180.000000     6.00000

In [16]:
pokemon.loc[:50,['HP','Defense']].to_csv('../data/pokemon_tmp.csv')

### 数据缺失

[reference](https://pandas.pydata.org/pandas-docs/stable/missing_data.html)

In [18]:
pokemon.loc[10:16,:]

#                     Name Type 1  Type 2  Total  HP  Attack  Defense  \
10   8                Wartortle  Water     NaN    405  59      63       80   
11   9                Blastoise  Water     NaN    530  79      83      100   
12   9  BlastoiseMega Blastoise  Water     NaN    630  79     103      120   
13  10                 Caterpie    Bug     NaN    195  45      30       35   
14  11                  Metapod    Bug     NaN    205  50      20       55   
15  12               Butterfree    Bug  Flying    395  60      45       50   
16  13                   Weedle    Bug  Poison    195  40      35       30   

    Sp. Atk  Sp. Def  Speed  Generation  Legendary  
10       65       80     58           1      False  
11       85      105     78           1      False  
12      135      115     78           1      False  
13       20       20     45           1      False  
14       25       25     30           1      False  
15       90       80     70           1      False  
16       20       20     50           1      False

In [88]:
pokemon.loc[pokemon["Type 2"].isnull(), "Type 2"] = pokemon.loc[pokemon["Type 2"].isnull(), "Type 1"]
pokemon.head(10)

#                       Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1                  Bulbasaur  Grass  Poison    318  45      49       49   
1  2                    Ivysaur  Grass  Poison    405  60      62       63   
2  3                   Venusaur  Grass  Poison    525  80      82       83   
3  3      VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4                 Charmander   Fire    Fire    309  39      52       43   
5  5                 Charmeleon   Fire    Fire    405  58      64       58   
6  6                  Charizard   Fire  Flying    534  78      84       78   
7  6  CharizardMega Charizard X   Fire  Dragon    634  78     130      111   
8  6  CharizardMega Charizard Y   Fire  Flying    634  78     104       78   
9  7                   Squirtle  Water   Water    314  44      48       65   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False  
5       80       65     80           1      False  
6      109       85    100           1      False  
7      130       85    100           1      False  
8      159      115    100           1      False  
9       50       64     43           1      False

In [89]:
pokemon.isnull().head()

#   Name  Type 1  Type 2  Total     HP  Attack  Defense  Sp. Atk  \
0  False  False   False   False  False  False   False    False    False   
1  False  False   False   False  False  False   False    False    False   
2  False  False   False   False  False  False   False    False    False   
3  False  False   False   False  False  False   False    False    False   
4  False  False   False   False  False  False   False    False    False   

   Sp. Def  Speed  Generation  Legendary  
0    False  False       False      False  
1    False  False       False      False  
2    False  False       False      False  
3    False  False       False      False  
4    False  False       False      False

In [90]:
apts.isnull()

Beijing      False
Shanghai     False
Shenzhen     False
Hangzhou     False
Guangzhou    False
Suzhou        True
Name: price, dtype: bool

In [91]:
apts.notnull()

Beijing       True
Shanghai      True
Shenzhen      True
Hangzhou      True
Guangzhou     True
Suzhou       False
Name: price, dtype: bool

In [92]:
print(apts[apts.isnull()])

Suzhou   NaN
Name: price, dtype: float64


In [93]:
print(apts[apts.isnull() == False]) #根据是否缺失选择数据

Beijing      55000.0
Shanghai     60000.0
Shenzhen     55000.0
Hangzhou     40000.0
Guangzhou    40000.0
Name: price, dtype: float64


用to_csv方法写出到文件

In [94]:
import numpy as np
df = pd.DataFrame(np.random.rand(10, 4), columns=list("abcd"))
df

a         b         c         d
0  0.569415  0.468089  0.260840  0.172120
1  0.288680  0.771640  0.465192  0.979539
2  0.095298  0.385866  0.983792  0.412143
3  0.903898  0.327998  0.134250  0.948132
4  0.955035  0.838292  0.932714  0.630797
5  0.210932  0.428113  0.937603  0.650599
6  0.661533  0.390347  0.080175  0.159178
7  0.018230  0.961200  0.043113  0.877882
8  0.381884  0.314338  0.273786  0.200851
9  0.454861  0.283102  0.969393  0.404643

In [95]:
df.to_csv("../data/sample.tsv", sep="\t")

In [96]:
df.add(pd.Series(np.ones(10)) * 10, axis=0)

a          b          c          d
0  10.569415  10.468089  10.260840  10.172120
1  10.288680  10.771640  10.465192  10.979539
2  10.095298  10.385866  10.983792  10.412143
3  10.903898  10.327998  10.134250  10.948132
4  10.955035  10.838292  10.932714  10.630797
5  10.210932  10.428113  10.937603  10.650599
6  10.661533  10.390347  10.080175  10.159178
7  10.018230  10.961200  10.043113  10.877882
8  10.381884  10.314338  10.273786  10.200851
9  10.454861  10.283102  10.969393  10.404643

### 数据删除
DataFrame中的数据删除，可以用drop完成，需要特别注意的是，DataFrame的很多操作(包括drop)都有一个inplace参数，默认inplace=False，我们会对数据进行变换(比如删除行列)然后以返回值形态返回结果，如果inplace=True则会就地变换。

In [97]:
frame

year       city  population   debt
one    2016    Beijing        2200    NaN
two    2017   Shanghai        2300  100.0
three  2016  Guangzhou        1000  200.0
four   2017   Shenzhen         700    NaN
five   2016   Hangzhou         500  300.0
six       0          0           0    NaN

In [98]:
frame.drop(["one", "two"])

year       city  population   debt
three  2016  Guangzhou        1000  200.0
four   2017   Shenzhen         700    NaN
five   2016   Hangzhou         500  300.0
six       0          0           0    NaN

drop不仅仅可以删除行，还可以删除列

In [99]:
frame.drop('debt', axis=1)

year       city  population
one    2016    Beijing        2200
two    2017   Shanghai        2300
three  2016  Guangzhou        1000
four   2017   Shenzhen         700
five   2016   Hangzhou         500
six       0          0           0